//
//  ChannelBuilder.swift
//  Dela
//
//  Created by Alexander Herlin on 2021-01-15.
//

import Foundation
import GRPC
import Logging
import NIOHPACK
import NIO
import Combine

class RemoteChannel {

    let clientConnection: ClientConnection
    let clientConfiguration: ClientConnection.Configuration
    let defaultCallOptions: CallOptions
	let connectivitySubject = PassthroughSubject<ConnectivityState, Never>()
    private let group: MultiThreadedEventLoopGroup

    static var shared = RemoteChannel()

    init() {
		let connectivityHandler = ConnectivityHandler()

        group = MultiThreadedEventLoopGroup(numberOfThreads: 5)
        clientConfiguration = ClientConnection.Configuration(
            target: .hostAndPort(InfoKey.apiUrl.value, Int(InfoKey.apiPort.value) ?? 0),
            eventLoopGroup: group,
            connectivityStateDelegate: connectivityHandler)

        clientConnection = ClientConnection(configuration: clientConfiguration)
        print("Adress: \(InfoKey.apiUrl.value):\(Int(InfoKey.apiPort.value) ?? 0)")
        print("Connection Status=>:\(clientConnection.connectivity.state)")

        defaultCallOptions = CallOptions(
            customMetadata: HPACKHeaders([("x-user", UUID().uuidString)]),
            timeLimit: .none,
            messageEncoding: .disabled,
            requestIDProvider: CallOptions.RequestIDProvider.autogenerated,
            requestIDHeader: UUID().uuidString,
            cacheable: false,
            logger: Logger(label: "io.grpc", factory: { _ in SwiftLogNoOpLogHandler() }))

		connectivityHandler.onChange = { state in
			self.connectivitySubject.send(state)
		}
    }

    deinit {
        do {
            try group.syncShutdownGracefully()
        } catch {}
    }
}
