# docker-compose -f stack.yml up
version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    deploy:
      replicas: 1
    environment:
      MONGO_INITDB_ROOT_USERNAME: kronk
      MONGO_INITDB_ROOT_PASSWORD: 5RwjSCNN
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    deploy:
      replicas: 1
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kronk
      ME_CONFIG_MONGODB_ADMINPASSWORD: 5RwjSCNN
